"""empty message

Revision ID: 15ab7696fb24
Revises: 
Create Date: 2018-12-14 09:49:57.359926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15ab7696fb24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('light_pattern', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('error_code'),
    sa.UniqueConstraint('light_pattern')
    )
    op.create_table('moon_phase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('display_name', sa.String(length=16), nullable=False),
    sa.Column('light_pattern', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('light_pattern')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moon_phase')
    op.drop_table('error_code')
    # ### end Alembic commands ###
