"""created MoonPhase table

Revision ID: d8bc025a1007
Revises: 30e0c43f66d0
Create Date: 2018-12-13 17:22:45.940883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8bc025a1007'
down_revision = '30e0c43f66d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moon_phase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=True),
    sa.Column('display_name', sa.String(length=16), nullable=True),
    sa.Column('light_pattern', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('light_pattern')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moon_phase')
    # ### end Alembic commands ###
